### PR TITLE
feat(xss_api): Replace sanitizer with DOMPurify

### LINKED ISSUE #52: Replace sanitizer with DOMPurify
xss_api.js currently uses [Caja-HTML-Sanitizer](https://github.com/theSmaw/Caja-HTML-Sanitizer) for filterHTML(). As suggested by @lkrapf [here](https://github.com/adobe/helix-pipeline/pull/263#issuecomment-484042946), [DOMPurify](https://github.com/cure53/DOMPurify) would be a more proven alternative with a very active community (while Caja-HTML-Sanitizer only has 48 commits and was last updated 3 years ago).

I propose to replace it with DOMPurify.

### PR DESCRIPTION
**Pull request by rofe**
Fix #52

### CODE REVIEW

**Comment by trieloff** [comment]
What I've seen so far of DOMPurify seems to be a bit heavy-handed (i.e. the default config removes `id` attributes) and I'm sure there are legitimate reasons for having `javascript` in `href` attributes (no matter if it is no longer a best practice).

While the addition of JSDOM is no problem for Helix, it will make it harder to use htlengine in a browser.

**Comment by rofe** [comment]
> the default config removes `id` attributes

What makes you say that?

**Comment by trieloff** [comment]
The discussion I had with @ramboz lead me to the conclusion. Reading the DOM-Purify code https://github.com/cure53/DOMPurify/blob/c57dd450d8613fddfda67ad182526f371b4638fd/src/purify.js#L720-L728 it only removes `id` and `name` attributes that are in the DOM `document` or `form` API, which is ok.

**Comment by rofe** [comment]
Ok. I can't reproduce general `id` removal either. I'm open to alternatives of course, but unless there are any more concerns with DOMPurify, I think it's a much safer bet than Caja-HTML-Sanitizer: 20x commits, 14x releases, 6x contributors, and the last commit is 5 days old (Added missing SVG filter attributes) vs 3 years (!) ago in Caja...

**Comment by rofe** [comment]
> use htlengine in a browser

Is that a real goal atm? If so, I think we would run into many more issues, e.g. with the `fs-extra` dependency...

**Comment by ramboz** [comment]
DOMPurify will remove `id` and `name` if it detects a DOM CLobbering attack, i.e. use an `id` or `name` that is already a property defined on the `document` object. So you should be able to trigger the removal with things like:
- id="location"
- id="name"
- id="addEventListener"
- id="removeEventListener"
- …

**Comment by ramboz** [comment]
>  I'm sure there are legitimate reasons for having javascript in href attributes

You'll probably always find a _legitimate_ use case for it. It's mostly a subjective opinion on what legitimate is in each context. For HTL, I would expect the engine to remove them by default, and let me add them if I specify an `unsafe` context. So maximum security by default, and conscious decision to open some doors if needed

**Comment by rofe** [comment]
> let me add them if I specify an `unsafe` context.

That is already the case: context `unsafe` will not sanitize anything. And DOMPurify will currently only be used for context `html`. You could still use `javascript` URLs by using context `uri` (see #53 for that).

We can still add a [config](https://github.com/cure53/DOMPurify/#can-i-configure-dompurify) later if customers need to tweak it. But I would try to stick with the default (empty) config for as long as possible.

**Comment by tripodsan** [comment]
why not just use the same regexp as in sling:

This is the regexp Sling uses to validate href's:
https://github.com/apache/sling-org-apache-sling-xss/blob/5071a142cdfeaf128a0db1ed5222b4e3753303c9/src/main/resources/SLING-INF/content/config.xml#L76

built from this code:
https://github.com/apache/sling-org-apache-sling-xss/blob/5071a142cdfeaf128a0db1ed5222b4e3753303c9/src/main/java/org/apache/sling/xss/impl/XSSFilterImpl.java#L84

**Comment by rofe** [comment]
Oops, GitHawk snafu - I just replaced @tripodsan’s comment instead of replying to it 🙄 sorry!

**Comment by tripodsan** [comment]
shouldn't we use dom purify then for all https://github.com/adobe/htl-spec/blob/master/SPECIFICATION.md#121-display-context ?

**Comment by rofe** [comment]
> can you add tests where the current sanitizer produces wrong output?

it doesn't produce wrong output. #52 is an enhancement. It's about switching to a safer choice for sanitization than the current sanitizer.

**Comment by rofe** [comment]
> shouldn't we use dom purify then for all (...)

That's not possible, I'm afraid. Its only API method `sanitize` takes an HTML string, so you can't just pass it a URI or attribute value. But we currently use `sanitizer` for the `html` context only, too. I think each context has its own challenges, and using a distinct library for each isn't necessarily a bad thing. If there is a well maintained sanitizer library out there that can handle multiple contexts, I'm all for consolidating.

**Comment by rofe** [comment]
> I still think we need some tests

The tests remain the same (and are still passing), we're just switching the library behind `filterHTML()`. I'd have to find specific cases where the current sanitization is worse than DOMPurify, but I'm afraid that would be beside the point of #52, which was to replace a security library that's basically been dead for 3 years with one that's very lively...

**Comment by tripodsan** [comment]
i'm more concerned about the long dependency list of jsdom:

```
├─┬ jsdom@15.0.0
│ ├── abab@2.0.0
│ ├── acorn@6.1.1
│ ├─┬ acorn-globals@4.3.2
│ │ ├── acorn@6.1.1 deduped
│ │ └── acorn-walk@6.1.1
│ ├── array-equal@1.0.0
│ ├── cssom@0.3.6
│ ├─┬ cssstyle@1.2.2
│ │ └── cssom@0.3.6 deduped
│ ├─┬ data-urls@1.1.0
│ │ ├── abab@2.0.0 deduped
│ │ ├── whatwg-mimetype@2.3.0 deduped
│ │ └── whatwg-url@7.0.0 deduped
│ ├─┬ domexception@1.0.1
│ │ └── webidl-conversions@4.0.2 deduped
│ ├─┬ escodegen@1.11.1
│ │ ├── esprima@3.1.3
│ │ ├── estraverse@4.2.0
│ │ ├── esutils@2.0.2
│ │ ├─┬ optionator@0.8.2
│ │ │ ├── deep-is@0.1.3
│ │ │ ├── fast-levenshtein@2.0.6
│ │ │ ├─┬ levn@0.3.0
│ │ │ │ ├── prelude-ls@1.1.2 deduped
│ │ │ │ └── type-check@0.3.2 deduped
│ │ │ ├── prelude-ls@1.1.2
│ │ │ ├─┬ type-check@0.3.2
│ │ │ │ └── prelude-ls@1.1.2 deduped
│ │ │ └── wordwrap@1.0.0
│ │ └── source-map@0.6.1
│ ├─┬ html-encoding-sniffer@1.0.2
│ │ └── whatwg-encoding@1.0.5 deduped
│ ├── nwsapi@2.1.4
│ ├── parse5@5.1.0
│ ├── pn@1.1.0
│ ├─┬ request@2.88.0
│ │ ├── aws-sign2@0.7.0
│ │ ├── aws4@1.8.0
│ │ ├── caseless@0.12.0
│ │ ├─┬ combined-stream@1.0.7
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@3.0.2
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@2.3.3
│ │ │ ├── asynckit@0.4.0
│ │ │ ├── combined-stream@1.0.7 deduped
│ │ │ └── mime-types@2.1.24 deduped
│ │ ├─┬ har-validator@5.1.3
│ │ │ ├─┬ ajv@6.10.0
│ │ │ │ ├── fast-deep-equal@2.0.1
│ │ │ │ ├── fast-json-stable-stringify@2.0.0
│ │ │ │ ├── json-schema-traverse@0.4.1
│ │ │ │ └─┬ uri-js@4.2.2
│ │ │ │   └── punycode@2.1.1 deduped
│ │ │ └── har-schema@2.0.0
│ │ ├─┬ http-signature@1.2.0
│ │ │ ├── assert-plus@1.0.0
│ │ │ ├─┬ jsprim@1.4.1
│ │ │ │ ├── assert-plus@1.0.0 deduped
│ │ │ │ ├── extsprintf@1.3.0
│ │ │ │ ├── json-schema@0.2.3
│ │ │ │ └─┬ verror@1.10.0
│ │ │ │   ├── assert-plus@1.0.0 deduped
│ │ │ │   ├── core-util-is@1.0.2
│ │ │ │   └── extsprintf@1.3.0 deduped
│ │ │ └─┬ sshpk@1.16.1
│ │ │   ├─┬ asn1@0.2.4
│ │ │   │ └── safer-buffer@2.1.2 deduped
│ │ │   ├── assert-plus@1.0.0 deduped
│ │ │   ├─┬ bcrypt-pbkdf@1.0.2
│ │ │   │ └── tweetnacl@0.14.5 deduped
│ │ │   ├─┬ dashdash@1.14.1
│ │ │   │ └── assert-plus@1.0.0 deduped
│ │ │   ├─┬ ecc-jsbn@0.1.2
│ │ │   │ ├── jsbn@0.1.1 deduped
│ │ │   │ └── safer-buffer@2.1.2 deduped
│ │ │   ├─┬ getpass@0.1.7
│ │ │   │ └── assert-plus@1.0.0 deduped
│ │ │   ├── jsbn@0.1.1
│ │ │   ├── safer-buffer@2.1.2 deduped
│ │ │   └── tweetnacl@0.14.5
│ │ ├── is-typedarray@1.0.0
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├─┬ mime-types@2.1.24
│ │ │ └── mime-db@1.40.0
│ │ ├── oauth-sign@0.9.0
│ │ ├── performance-now@2.1.0
│ │ ├── qs@6.5.2
│ │ ├── safe-buffer@5.1.2
│ │ ├─┬ tough-cookie@2.4.3
│ │ │ ├── psl@1.1.31 deduped
│ │ │ └── punycode@1.4.1
│ │ ├─┬ tunnel-agent@0.6.0
│ │ │ └── safe-buffer@5.1.2 deduped
│ │ └── uuid@3.3.2
│ ├─┬ request-promise-native@1.0.7
│ │ ├─┬ request-promise-core@1.1.2
│ │ │ └── lodash@4.17.11 deduped
│ │ ├── stealthy-require@1.1.1
│ │ └── tough-cookie@2.5.0 deduped
│ ├─┬ saxes@3.1.9
│ │ └── xmlchars@1.3.1
│ ├── symbol-tree@3.2.2
│ ├─┬ tough-cookie@2.5.0
│ │ ├── psl@1.1.31
│ │ └── punycode@2.1.1
│ ├─┬ w3c-hr-time@1.0.1
│ │ └── browser-process-hrtime@0.1.3
│ ├─┬ w3c-xmlserializer@1.1.2
│ │ ├── domexception@1.0.1 deduped
│ │ ├── webidl-conversions@4.0.2 deduped
│ │ └── xml-name-validator@3.0.0 deduped
│ ├── webidl-conversions@4.0.2
│ ├─┬ whatwg-encoding@1.0.5
│ │ └─┬ iconv-lite@0.4.24
│ │   └── safer-buffer@2.1.2
│ ├── whatwg-mimetype@2.3.0
│ ├─┬ whatwg-url@7.0.0
│ │ ├── lodash.sortby@4.7.0
│ │ ├─┬ tr46@1.0.1
│ │ │ └── punycode@2.1.1 deduped
│ │ └── webidl-conversions@4.0.2 deduped
│ ├─┬ ws@6.2.1
│ │ └── async-limiter@1.0.0
│ └── xml-name-validator@3.0.0
```

and it kind of bugs me, that we already have a HTML parser in the HTL engine, and create a DOM again...

**Comment by rofe** [comment]
I understand... do we have already have a window-like object we could pass to `createDOMPurify()`?

**Comment by tripodsan** [comment]
would be interresting to see why jsdom is needed at all....

**Comment by rofe** [comment]
It looks like (well, the name suggests that) DOMPurify is largely depending on a DOM API, either the browser's or a virtual one:
https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L64

**Comment by rofe** [comment]
Decision taken to close this PR unmerged. See #52.

**Pull request closed without merging**
