### PR TITLE
implement support for data-sly-unwrap

### LINKED ISSUE #43: implement support for data-sly-unwrap
see https://github.com/adobe/htl-spec/blob/master/SPECIFICATION.md#2211-unwrap

### PR DESCRIPTION
**Pull request by znikolovski**
Fix #43

### CODE REVIEW

**Comment by trieloff** [comment]
This pull request **introduces 1 alert** when merging 72a6e39deac0efdd0bd7ebcfd1b4c6dae62352d1 into 0ccc21874186f9da1ca43c7b8d9ba23eddfaddd3 - [view on LGTM.com](https://lgtm.com/projects/g/adobe/htlengine/rev/pr-b21ada36053190da71aa8ef1a0e447dfb984a62f)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by trieloff** [comment]
Thanks for the PR, @znikolovski – do you have tests, too?

**Comment by znikolovski** [comment]
@trieloff I've added tests but the CI check fails one of the tests (which seem to all work correctly locally). Looking at the output it seems like an extra "\n" is being added to the end of the expected value:
AssertionError [ERR_ASSERTION]: '<span>yes</span>\n' == '<span>yes</span>\n\n'

**Comment by tripodsan** [comment]
@znikolovski thanks for the tests. the problem with the EOF lineending is common :-) 
please use a trailing comment, like in https://github.com/adobe/htlengine/blob/master/test/specs/simple_spec.txt#L185-L186

**Comment by znikolovski** [comment]
@tripodsan thanks for the heads up! :)

If you look at the spec file I actually do use a trailing comment and it's still failing :/

**Comment by tripodsan** [comment]
> If you look at the spec file I actually do use a trailing comment and it's still failing :/

not here: https://github.com/adobe/htlengine/pull/55/files#diff-bde51beb7ef3b88dcf54a5f8e8eeb759R26 

:-)

**Comment by znikolovski** [comment]
@tripodsan I have no idea what happened but my unwrap spec got blended into the template spec...all good now!

**Comment by tripodsan** [comment]
@trieloff it seems that circleci doesn't run on foreign branches...is there something we can do?

**Comment by trieloff** [comment]
Screen Shot 2019-05-07 at 10 10 39

Yes, change these settings (already done)

**Pull request merged**
